name: "trained_testmodel"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
  {
    name: "x__0"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
output [
  {
    name: "logits__0"
    data_type: TYPE_FP32
    dims: [ 1  ]
  }
]
